dynamic_background_opacity yes
background_opacity 0
background_blur 0
foreground   #ecdbd3
background   #110d12
cursor       #ecdbd3

color0       #110d12
color8       #a59993
color1       #A2304B
color9       #A2304B
color2       #E80E50
color10      #E80E50
color3       #E12658
color11      #E12658
color4       #7C7787
color12      #7C7787
color5       #A59CA8
color13      #A59CA8
color6       #CAB1AF
color14      #CAB1AF
color7       #ecdbd3
color15      #ecdbd3
