font=Mononoki Nerd Font:pixelsize=16

#[colors]
#foreground = A3D7E3
#background = 051820
#regular0 = 051820
#regular1 = 106B92
#regular2 = 4574A4
#regular3 = 1295A5
#regular4 = 6193B0
#regular5 = 0DA8D6
#regular6 = 0DD6EA
#regular7 = a3d7e3
#bright0 = 72969e
#bright1 = 106B92
#bright2 = 4574A4
#bright3 = 1295A5
#bright4 = 6193B0
#bright5 = 0DA8D6
#bright6 = 0DD6EA
#bright7 = a3d7e3
