# Shell variables
# Generated by 'wal'
wallpaper="/home/lain/mpv-shot0002.jpg"

# Special
background='#0f1c22'
foreground='#c3c6c7'
cursor='#c3c6c7'

# Colors
color0='#0f1c22'
color1='#116B92'
color2='#4574A4'
color3='#1295A5'
color4='#6193B0'
color5='#0EA8D6'
color6='#0DD6EA'
color7='#c3c6c7'
color8='#5e6c73'
color9='#116B92'
color10='#4574A4'
color11='#1295A5'
color12='#6193B0'
color13='#0EA8D6'
color14='#0DD6EA'
color15='#c3c6c7'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
