[colors]
background = '#0f1c228e'
black = '#0f1c22'
blue = '#116B92'
cursor = '#c3c6c7'
cyan = '#4574A4'
foreground = '#c3c6c7'
green = '#1295A5'
magenta = '#6193B0'
red = '#0EA8D6'
tabs = '#c3c6c7'
tabs-active = '#0DD6EA'
white = '#c3c6c7'
yellow = '#c3c6c7'
dim-black = '#0f1c228e'
dim-blue = '#116B928e'
dim-cyan = '#4574A48e'
dim-foreground = '#c3c6c78e'
dim-green = '#1295A58e'
dim-magenta = '#6193B08e'
dim-red = '#0EA8D68e'
dim-white = '#0DD6EA8e'
dim-yellow = '#c3c6c78e'
light-black = '#116B92'
light-blue = '#4574A4'
light-cyan = '#1295A5'
light-foreground = '#6193B0'
light-green = '#0EA8D6'
light-magenta = '#0DD6EA'
light-red = '#c3c6c7'
light-white = '#116B92'
light-yellow = '#4574A4'
