[colors.primary]
background = "#0f1c22"
foreground = "#c3c6c7"

[colors.cursor]
text = "#0f1c22"
cursor = "#c3c6c7"

[colors.vi_mode_cursor]
text = "#0f1c22"
cursor = "#c3c6c7"

[colors.search.matches]
foreground = "#0f1c22"
background = "#c3c6c7"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#5e6c73"
background = "#c3c6c7"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#0f1c22"
red = "#116B92"
green = "#4574A4"
yellow = "#1295A5"
blue = "#6193B0"
magenta = "#0EA8D6"
cyan = "#0DD6EA"
white = "#c3c6c7"

[colors.bright]
black = "#5e6c73"
red = "#116B92"
green = "#4574A4"
yellow = "#1295A5"
blue = "#6193B0"
magenta = "#0EA8D6"
cyan = "#0DD6EA"
white = "#c3c6c7"

[colors.dim]
black = "#c3c6c7"
red = "#116B92"
green = "#0EA8D6"
yellow = "#1295A5"
blue = "#6193B0"
magenta = "#4574A4"
cyan = "#0DD6EA"
white = "#5e6c73"

