# pywal theme for ghostty

background = 0f1c22
foreground = c3c6c7
cursor-color = c3c6c7
selection-background = c3c6c7
selection-foreground = 0f1c22

palette = 0=#0f1c22
palette = 1=#116B92
palette = 2=#4574A4
palette = 3=#1295A5
palette = 4=#6193B0
palette = 5=#0EA8D6
palette = 6=#0DD6EA
palette = 7=#c3c6c7
palette = 8=#5e6c73
palette = 9=#116B92
palette = 10=#4574A4
palette = 11=#1295A5
palette = 12=#6193B0
palette = 13=#0EA8D6
palette = 14=#0DD6EA
palette = 15=#c3c6c7
